apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: model
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model-container
        image: your-docker-image
        ports:
        - containerPort: 8000